# gym-api/src/main/resources/application.yml
server:
  port: ${PORT:8080}

spring:
  application:
    name: gym-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gymdb}
    username: ${SPRING_DATASOURCE_USERNAME:gym}
    password: ${SPRING_DATASOURCE_PASSWORD:gym}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

management:
  endpoints:
    web:
      exposure:
        include: health,info

# fora de "spring"!
storage:
  local:
    base-path: ${STORAGE_LOCAL_BASE_PATH:./storage}

security:
  jwt:
    secret: ${JWT_SECRET:change-me-please-change-me-please-change-me}
    expiration-seconds: ${JWT_EXP_SECONDS:3600}

checkin:
  callback-secret: ${CHECKIN_CALLBACK_SECRET:change-me-please}

payments:
  hmac-secret: ${PAYMENTS_HMAC_SECRET:change-hmac}
  callback-secret: ${PAYMENTS_CALLBACK_SECRET:change-me-too}
  scheduler:
    cron: "0 * * * * *"
  max-attempts: 3
  retry-backoff-minutes: 60
  mock:
    accept: true
  past-due:
    cancel-future-bookings: true
    grace-hours: 0

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:*}

ratelimit:
  bookings:
    book-min-interval-ms: ${RL_BOOK_MIN_MS:800}     # minimum gap between /book calls per user
    cancel-min-interval-ms: ${RL_CANCEL_MIN_MS:800}   # minimum gap between /cancel calls per user

bootstrap:
  admin:
    email: ${BOOTSTRAP_ADMIN_EMAIL:}
    password: ${BOOTSTRAP_ADMIN_PASSWORD:}    